# Portfolio assignment 7: Relational databases

```{r setup xx, include=FALSE}
knitr::opts_chunk$set(warning=FALSE,message=FALSE)

#install.packages("dslabs")

library(tidyverse)
library(dslabs) #package met gapminder dataset
```


```{r flu, dengue en gapminder data inlezen}
gapminder_df <- as.data.frame(gapminder)

gapminder_df

flu_df <- as.data.frame(read.csv(here::here(
  "flu_data.csv"), skip = 11))

flu_df

dengue_df <- as.data.frame(read.csv(here::here(
  "dengue_data.csv"), skip = 11))

dengue_df
```

```{r dataframes tidy maken}
flu_df <- pivot_longer(data = flu_df, cols=c(2:30), names_to = "Country", values_to = "Influenza_activity")

dengue_df <- pivot_longer(data = dengue_df, cols=c(2:11), names_to = "Country", values_to = "Dengue_activity")

#gapminder was al tidy
```

Country in flu en dengue is met een hoofdletter C en type character. Country in gapminder is met een kleine letter c en type factor.
Date als character in flu en dengue, year in gapminder als integer.

```{r kolommen met land en jaartal hetzelfde maken voor de drie dataframes}
#...
flu_df <- separate(data = flu_df, col = Date, into = c("Year", "Month", "Day"), sep = "-")
dengue_df <- separate(data = dengue_df, col = Date, into = c("Year", "Month", "Day"), sep = "-")

#...
flu_df$Country <- as.factor(flu_df$Country)
dengue_df$Country <- as.factor(dengue_df$Country)

flu_df$Year <- as.integer(flu_df$Year)
dengue_df$Year <- as.integer(dengue_df$Year)

#Alle drie dezelfde kolomnamen:
gapminder_df <- rename(gapminder_df, Year = year)
gapminder_df <- rename(gapminder_df, Country = country)

#...
## via https://stackoverflow.com/questions/25089665/error-only-defined-on-a-data-frame-with-all-numeric-variables-with-ddply-on-lar
flu_df <- flu_df %>% group_by(Country, Year) %>% summarise_each(funs(sum),Influenza_activity)

dengue_df <- dengue_df %>% group_by(Country, Year) %>% summarise_each(funs(sum),Dengue_activity)

#Maak er opnieuw dataframes van:
flu_df <- as.data.frame(flu_df)
dengue_df <- as.data.frame(dengue_df)

#Schrijf de drie dataframes om naar .csv en .rds:
write.csv(gapminder_df, file = "gapminder_df.csv")
write.csv(flu_df, file = "flu_df.csv")
write.csv(dengue_df, file = "dengue_df.csv")

saveRDS(gapminder_df, "C:/Users/steph/DSFB2/portfolio_book/gapminder_df.rds")
saveRDS(flu_df, "C:/Users/steph/DSFB2/portfolio_book/flu_df.rds")
saveRDS(dengue_df, "C:/Users/steph/DSFB2/portfolio_book/dengue_df.rds")
```

```{r van RStudio naar DBeaver,eval=FALSE}
library(DBI)

con <- dbConnect(RPostgres::Postgres(),
                 dbname = "workflowsdb",
                 host="localhost",
                 port="5432",
                 user="postgres",
                 password="...")

dbWriteTable(con, "flu_df", flu_df)

dbWriteTable(con, "dengue_df", dengue_df)

dbWriteTable(con, "gapminder_df", gapminder_df)

dbDisconnect(con)
```

```{r DBeaver inspection of content}
#Om een of andere reden moet ik nu ineens 'dd' opgeven achter de tabel en dd."..." voor een kolom?

#Naast het aanklikken en doornemen Data, Properties en ER Diagram van de tabellen, heb ik de data geïnspecteerd met de volgende queries:

#SELECT
#dd."Country",
#dd."Dengue_activity",
#dd."Year"
#FROM dengue_df dd 
#WHERE "Year"=2009;

#SELECT
#dd."Country",
#dd."Influenza_activity",
#dd."Year"
#FROM flu_df dd 
#WHERE "Year"=2009;

#SELECT
#dd."Country",
#dd."infant_mortality",
#dd."Year"
#FROM gapminder_df dd 
#WHERE "Year"=2009;

#SELECT
#dd."Country",
#dd."Dengue_activity",
#dd."Year"
#FROM dengue_df dd 
#ORDER BY
#dd."Dengue_activity" asc

#SELECT
#dd."Country",
#dd."Influenza_activity",
#dd."Year"
#FROM flu_df dd 
#ORDER BY
#dd."Influenza_activity" ASC;

#SELECT
#dd."Country",
#dd."infant_mortality",
#dd."Year"
#FROM gapminder_df dd 
#ORDER BY
#dd."infant_mortality" ASC;

#SELECT
#DISTINCT dd."Year"
#FROM
#gapminder_df dd
#ORDER BY
#dd."Year" ASC;
```


```{r dplyr inspection of content}
class(dengue_df)
str(dengue_df)
summary(dengue_df)

class(flu_df)
str(flu_df)
summary(flu_df)

class(gapminder_df)
str(gapminder_df)
summary(gapminder_df)

#Bovenstaande queries zijn vertaald naar dezelfde analyse in R, wat dezelfde resultaten gaf:

dengue_df %>% filter(Year == 2009) %>% select(Country, Dengue_activity, Year)

flu_df %>% filter(Year == 2009) %>% select(Country, Influenza_activity, Year)

gapminder_df %>% filter(Year == 2009) %>% select(Country, infant_mortality, Year)



dengue_df %>% select(Country, Dengue_activity, Year) %>% arrange(Dengue_activity)

flu_df %>% select(Country, Influenza_activity, Year) %>% arrange(Influenza_activity)

gapminder_df %>% select(Country, infant_mortality, Year) %>% arrange(infant_mortality)

#Beter maar lukt niet in SQL: #gapminder_df %>% select(Country, infant_mortality, Year) %>% group_by(Country, Year) %>% summarise(infant_mortality) %>% arrange()



gapminder_df %>% select(Year) %>% arrange() %>% unique()
```

```{r}
#Load the gapminder data in R?
readRDS(here::here("gapminder_df.rds"))
readRDS(here::here("flu_df.rds"))
readRDS(here::here("dengue_df.rds"))

#Flu_df en dengue_df zijn "joinbaar" met elkaar...
flu_dengue <- left_join(flu_df, dengue_df, by = c("Country", "Year"))

#...en met gapminder_df
left_join(flu_dengue, gapminder_df, by = c("Country", "Year"))

#Het lijkt erop dat er niks veranderd hoeft te worden aan gapminder_df voor joinen in DBeaver met een compound key = waarde onder Country én Year i.p.v. een unieke identifiër voor eke Country + Year combo.

#select
#flu_df."Country",
#flu_df."Year" ,
#flu_df."Influenza_activity",
#dengue_df."Dengue_activity",
#gapminder_df."infant_mortality",
#gapminder_df."life_expectancy",
#gapminder_df."fertility",
#gapminder_df."population",
#gapminder_df."gdp",
#gapminder_df."continent",
#gapminder_df."region"
#from
#flu_df
#left join dengue_df
#on dengue_df."Country" = flu_df."Country" 
#and dengue_df."Year" = flu_df."Year"
#left join gapminder_df
#on gapminder_df."Country" = flu_df."Country"
#and gapminder_df."Year" = flu_df."Year";

flu_dengue_gapminder <- read_csv(here::here("flu_dengue_gapminder.csv"))

flu_dengue_gapminder
summary(flu_dengue_gapminder)

#Beschrijvende statistiek: tabel met per land per de gem. Influenza en Knokkelkoorts activiteit, de gem. kindersterfte, de gem. levensverwachting, het gem. aantal geboorten en de gem. populatie grootte.

## SLAAT NERGENS OP?! PER JAAR!
FLU <- flu_dengue_gapminder %>% group_by(Country) %>% summarise(Gem_Influenza_act = mean(Influenza_activity))
DENG <- flu_dengue_gapminder %>% group_by(Country) %>% summarise(Gem_Knokkelkoorts_act = mean(Dengue_activity))
MORT <- flu_dengue_gapminder %>% group_by(Country) %>% summarise(Gem_kindersterfte = mean(infant_mortality))
LIFE <- flu_dengue_gapminder %>% group_by(Country) %>% summarise(Gem_levensverwachting= mean(life_expectancy))
FERT <- flu_dengue_gapminder %>% group_by(Country) %>% summarise(Gem_geboorten = mean(fertility))
POPU <- flu_dengue_gapminder %>% group_by(Country) %>% summarise(Gem_populatie = mean(population))

desc_stat <- flu_dengue_gapminder %>% select(Country) %>% unique %>% mutate(FLU, DENG, MORT, LIFE, FERT, POPU)

##HIER MOOIE TABEL MAKEN MET KNITR

#desc_stat <- rename(desc_stat, Land = Country)

#plot 1: Influenza activiteit door de jaren heen
fdg <- flu_dengue_gapminder %>% filter(Influenza_activity > 0)

ggplot(data = fdg, aes(x = Year, y = Influenza_activity)) +
  geom_line(aes(color = Country), alpha = 0.8) +
  labs(title = "Influenza activiteit door de jaren heen", subtitle = "Voor 29 landen het aantal Influenza gevallen van 2002 tot \nen met 2015.", x = "Jaar", y = "Influenza activiteit (gevallen)", color = "Land") +
  theme_bw()

#plot 2: Dengue activiteit door de jaren heen
fdg2 <- flu_dengue_gapminder %>% filter(Dengue_activity > 0)

ggplot(data = fdg2, aes(x = Year, y = Dengue_activity)) +
  geom_line(aes(color = Country), alpha = 0.8) +
  labs(title = "Knokkelkoorts activiteit door de jaren heen", subtitle = "Voor 4 landen het aantal Knokkelkoorts gevallen van 2002 tot \nen met 2015.", x = "Jaar", y = "Knokkelkoorts activiteit (gevallen)", color = "Land") +
  theme_bw()

#plot 3: Verband tussen Influenza_activity en infant_mortality per land door de jaren heen
fdg3 <- flu_dengue_gapminder %>% filter(Influenza_activity > 0 & infant_mortality > 0)

cor.test(fdg3$Influenza_activity, fdg3$infant_mortality, method=c("pearson")) #p-value = 0.6713, geen stat. sig. verband

cor_coefficient <- round(cor.test(fdg3$Influenza_activity, fdg3$infant_mortality, method=c("pearson"))$estimate,2)

ggplot(data = fdg3, aes(x = Influenza_activity, y = infant_mortality)) +
  geom_point(aes(color = Country), size = 1, alpha = 0.8) +
  geom_smooth(se=F, color = "red") +
  labs(title = "Verband tussen Influenza activiteit en kindersterfte wereldwijd", subtitle = "Voor 29 landen is van 2002 tot en met 2015 per jaar het \naantal Influenza gevallen en de sterfte onder kinderen gemeten.", y = "Kindersterfte (aantal)", x = "Influenza activiteit (gevallen)") +
  theme_bw() +
  annotate("text", x = 112500, y = 45, size = 4, color = "red", label = paste("Pearson's r = ", cor_coefficient))
```

