---
title: "Mijn Data Sciences portfolio"
subtitle: "Door: Stephanie de Wit <br> Datum: 15-05-22 <br><br> Welkom! Tijdens het tweede deel van de _Data Sciences for Biology_ minor te Hogeschool Utrecht, heb ik gewerkt aan een portfolio van mijn vaardigheden tot nu toe. Dit portfolio is gebouwd met het CRAN {bookdown} R package en wordt hier gepubliceerd via GitHub Pages."
site: bookdown::bookdown_site
documentclass: book
output:
  bookdown::gitbook:
    includes:
      before_body: hero-image.html
    css: portfolio_style.css
    number_sections: true
new_session: yes
bibliography: portfolio.bib
---

# Over mij
Ik ben een nieuwsgierige, scherpe en gedreven _Life Sciences_ studente van 24 jaar oud. Momenteel rond ik mijn derde studiejaar af met een Data Sciences minor en ben ik opzoek naar een uitdagende afstudeerstage. Ik smul van studiemateriaal over genetica, immunologie en tumorcelbiologie en werk graag met recombinante DNA technieken, celkweek en eiwit analyse technieken. Het is mijn ambitie om als moleculair bioloog onderzoek te doen naar het ontstaan, voorkomen en bestrijden van ziekten. Als ik niet aan het lezen ben in _Campbell, Biology_ of documentaires kijk over het heelal, ga ik graag tafelen met vrienden, dansen in de discotheek, naar het museum en op stedentripjes.

<br>
__Header afbeelding: afkomstig uit een online artikel van [The Economist](https://www.economist.com/science-and-technology/2020/02/22/mapping-cells-to-build-a-complete-atlas-of-the-human-body)__
